name: "${project.name}"
version: "${project.version}"
main: tk.skulk.plugin.core.Plugin
api-version: "1.19"
authors: [ RGBCube ]
description: The main plugin used for the Skulk Network Minecraft server.
website: skulk.tk
commands:
  tpa-accept: { }
  tpa-cancel: { }
  tpa: { }
  tpa-ignore-all: { }
  tpa-ignore: { }
  tpa-list-ignored: { }
  tpa-reject: { }
  home: { }
  home-delete: { }
  home-list: { }
  home-set: { }
  update-snp: { }